### PR TITLE
adding frontend folder, bootstraping react project

### PR DESCRIPTION
**Pull request by bhansa**
Created react project structure using create react app.

### CODE REVIEW

**Comment by inovizz** [comment]
@bhansa - I'm trying to find some experience Frontend Dev who can help us with expert inputs. However, for now, shall we merge this?

**Comment by inovizz** [comment]
@bhansa - you may want to make your commit messages imperative. Here is a reference for writing good commit messages - https://chris.beams.io/posts/git-commit/

**Comment by bhansa** [comment]
@inovizz we can go ahead and merge this, once done I will be pushing other changes once I have a high level mock up from @subuhani, he is working on some designs.

**Comment by inovizz** [comment]
Ok, I'm merging it for now.

**Pull request merged**
